// ─── All Product Data ──────────────────────────────────────────

export const CATEGORIES = [
  { id: 'all',         label: 'All Products',  icon: '🛍️',  color: '#6366f1' },
  { id: 'mobiles',     label: 'Mobiles',        icon: '📱',  color: '#ec4899' },
  { id: 'laptops',     label: 'Laptops',        icon: '💻',  color: '#3b82f6' },
  { id: 'tablets',     label: 'Tablets',        icon: '📲',  color: '#f59e0b' },
  { id: 'headphones',  label: 'Headphones',     icon: '🎧',  color: '#10b981' },
  { id: 'earbuds',     label: 'Earbuds',        icon: '🎵',  color: '#8b5cf6' },
  { id: 'smartwatches',label: 'Smartwatches',   icon: '⌚',  color: '#06b6d4' },
];

export const PRODUCTS = [
  // ─── Mobiles ───────────────────────────────────────────────
  {
    id: 1,
    name: 'iPhone 16',
    brand: 'Apple',
    category: 'mobiles',
    price: 89999,
    originalPrice: 99999,
    image: '/images/mobiles/iphone 16.jpeg',
    rating: 4.8,
    reviews: 3120,
    stock: 18,
    isNew: true,
    isFeatured: true,
    description: 'The iPhone 16 features the powerful A18 chip, an advanced 48MP camera system, and an all-day battery. Experience the future with Apple Intelligence, Dynamic Island, and a stunning Super Retina XDR display.',
    specs: {
      Display: '6.1" OLED, 2556×1179, 460 ppi',
      Processor: 'Apple A18 (3nm)',
      RAM: '8 GB',
      Storage: '128 GB / 256 GB / 512 GB',
      Camera: '48MP Main + 12MP Ultra Wide',
      Battery: '3561 mAh, 25W fast charge',
      OS: 'iOS 18',
      Connectivity: '5G, Wi-Fi 7, Bluetooth 5.3, NFC',
    },
    colors: ['Black', 'White', 'Pink', 'Teal', 'Ultramarine'],
    tags: ['5G', 'OLED', 'Face ID', 'iOS 18'],
  },
  {
    id: 2,
    name: 'iPhone 15',
    brand: 'Apple',
    category: 'mobiles',
    price: 79999,
    originalPrice: 89999,
    image: '/images/mobiles/iphone 15.jpeg',
    rating: 4.7,
    reviews: 5840,
    stock: 25,
    isNew: false,
    isFeatured: true,
    description: 'iPhone 15 introduces Dynamic Island, a 48MP camera, and a USB-C connector. Powered by the A16 Bionic chip, it delivers unmatched performance in a gorgeous new design.',
    specs: {
      Display: '6.1" OLED, 2556×1179, 460 ppi',
      Processor: 'Apple A16 Bionic',
      RAM: '6 GB',
      Storage: '128 GB / 256 GB / 512 GB',
      Camera: '48MP Main + 12MP Ultra Wide',
      Battery: '3877 mAh, 20W fast charge',
      OS: 'iOS 17 (upgradeable to 18)',
      Connectivity: '5G, Wi-Fi 6, Bluetooth 5.3, NFC',
    },
    colors: ['Black', 'Blue', 'Pink', 'Yellow', 'Green'],
    tags: ['5G', 'OLED', 'Dynamic Island', 'USB-C'],
  },
  {
    id: 3,
    name: 'Samsung Galaxy S24 Ultra',
    brand: 'Samsung',
    category: 'mobiles',
    price: 129999,
    originalPrice: 149999,
    image: '/images/mobiles/Samsung Galaxy S24 Ultra.jpeg',
    rating: 4.9,
    reviews: 2780,
    stock: 10,
    isNew: false,
    isFeatured: true,
    description: 'The Galaxy S24 Ultra is the ultimate smartphone, featuring the built-in S Pen, a 200MP camera, and Snapdragon 8 Gen 3 with Galaxy AI. A truly unprecedented powerhouse.',
    specs: {
      Display: '6.8" Dynamic AMOLED 2X, 3088×1440, 505 ppi',
      Processor: 'Snapdragon 8 Gen 3 (4nm)',
      RAM: '12 GB',
      Storage: '256 GB / 512 GB / 1 TB',
      Camera: '200MP Main + 50MP Periscope + 10MP + 12MP UW',
      Battery: '5000 mAh, 45W fast charge',
      OS: 'Android 14 / One UI 6.1',
      Connectivity: '5G, Wi-Fi 7, Bluetooth 5.3, NFC, S Pen',
    },
    colors: ['Titanium Black', 'Titanium Gray', 'Titanium Violet', 'Titanium Yellow'],
    tags: ['5G', 'S Pen', '200MP', 'AI', 'Titanium'],
  },
  {
    id: 4,
    name: 'OnePlus 13',
    brand: 'OnePlus',
    category: 'mobiles',
    price: 69999,
    originalPrice: 74999,
    image: '/images/mobiles/OnePlus 13.jpeg',
    rating: 4.6,
    reviews: 1980,
    stock: 22,
    isNew: true,
    isFeatured: false,
    description: 'OnePlus 13 delivers flagship-level performance with Snapdragon 8 Elite, Hasselblad triple cameras, and 100W SUPERVOOC charging that fills from 0 to 100% in just 36 minutes.',
    specs: {
      Display: '6.82" LTPO AMOLED, 3168×1440, 510 ppi',
      Processor: 'Snapdragon 8 Elite (3nm)',
      RAM: '12 GB / 16 GB',
      Storage: '256 GB / 512 GB',
      Camera: '50MP Hasselblad + 50MP Periscope + 50MP UW',
      Battery: '6000 mAh, 100W SUPERVOOC',
      OS: 'OxygenOS 15 / Android 15',
      Connectivity: '5G, Wi-Fi 7, Bluetooth 5.4, NFC',
    },
    colors: ['Black Eclipse', 'Arctic Dawn'],
    tags: ['5G', 'Hasselblad', '100W Charging', 'Snapdragon'],
  },

  // ─── Laptops ───────────────────────────────────────────────
  {
    id: 5,
    name: 'Dell XPS 13',
    brand: 'Dell',
    category: 'laptops',
    price: 129999,
    originalPrice: 149999,
    image: '/images/laptops/Dell XPS 13.jpeg',
    rating: 4.7,
    reviews: 1540,
    stock: 8,
    isNew: false,
    isFeatured: true,
    description: 'The Dell XPS 13 is the gold standard for ultrabooks. Ultra-slim, ultra-premium, with InfinityEdge display and Intel Core Ultra processors for blazing performance.',
    specs: {
      Display: '13.4" OLED Touch, 2880×1800, 400 nits',
      Processor: 'Intel Core Ultra 7 155H',
      RAM: '16 GB / 32 GB LPDDR5x',
      Storage: '512 GB / 1 TB NVMe SSD',
      Graphics: 'Intel Arc Graphics',
      Battery: '54 Whr, 60W fast charge',
      OS: 'Windows 11 Home',
      Ports: '2× Thunderbolt 4, microSD, 3.5mm',
    },
    colors: ['Platinum', 'Graphite'],
    tags: ['Intel Core Ultra', 'OLED', 'Ultrabook', 'Thunderbolt'],
  },
  {
    id: 6,
    name: 'Lenovo ThinkPad X1 Carbon Gen 12',
    brand: 'Lenovo',
    category: 'laptops',
    price: 159999,
    originalPrice: 179999,
    image: '/images/laptops/Lenovo ThinkPad X1 Carbon Gen 12.jpeg',
    rating: 4.8,
    reviews: 890,
    stock: 5,
    isNew: true,
    isFeatured: false,
    description: 'The legendary ThinkPad X1 Carbon Gen 12 redefines business excellence. MIL-SPEC tested durability, AI-powered performance, and an incredible IPS anti-glare display in a 1.12 kg chassis.',
    specs: {
      Display: '14" IPS Anti-glare, 2880×1800, 400 nits',
      Processor: 'Intel Core Ultra 7 164U',
      RAM: '16 GB / 32 GB / 64 GB LPDDR5x',
      Storage: '512 GB / 1 TB / 2 TB NVMe SSD',
      Graphics: 'Intel Graphics (Xe)',
      Battery: '57 Whr, 65W USB-C',
      OS: 'Windows 11 Pro',
      Ports: '2× Thunderbolt 4, 2× USB-A, HDMI, SD, 3.5mm',
    },
    colors: ['Deep Black'],
    tags: ['ThinkPad', 'MIL-SPEC', 'Intel Core Ultra', 'Business'],
  },
  {
    id: 7,
    name: 'Lenovo ThinkPad X2 Carbon Gen 12',
    brand: 'Lenovo',
    category: 'laptops',
    price: 149999,
    originalPrice: 169999,
    image: '/images/laptops/Lenovo ThinkPad X2 Carbon Gen 12.jpeg',
    rating: 4.6,
    reviews: 420,
    stock: 12,
    isNew: true,
    isFeatured: false,
    description: 'The ThinkPad X2 Carbon brings next-generation AI capabilities to a refined carbon-fiber chassis. Built for professionals who demand portability without compromise.',
    specs: {
      Display: '14" IPS, 2560×1600, 500 nits',
      Processor: 'Intel Core Ultra 5 125U',
      RAM: '16 GB LPDDR5x',
      Storage: '512 GB NVMe SSD',
      Graphics: 'Intel Arc Graphics',
      Battery: '52 Whr, 65W USB-C',
      OS: 'Windows 11 Pro',
      Ports: '2× Thunderbolt 4, 2× USB-A, HDMI',
    },
    colors: ['Deep Black'],
    tags: ['ThinkPad', 'Carbon Fiber', 'AI PC', 'Portable'],
  },

  // ─── Tablets ───────────────────────────────────────────────
  {
    id: 8,
    name: 'Apple MacBook Pro M4',
    brand: 'Apple',
    category: 'tablets',
    price: 199999,
    originalPrice: 219999,
    image: '/images/tablets/Apple MacBook Pro M4.jpeg',
    rating: 4.9,
    reviews: 2100,
    stock: 6,
    isNew: true,
    isFeatured: true,
    description: 'The MacBook Pro with M4 chip is the most powerful Mac laptop ever. Featuring Liquid Retina XDR display, up to 24 hours battery, and Apple Intelligence for unprecedented AI capability.',
    specs: {
      Display: '14.2" Liquid Retina XDR, 3024×1964, 1000 nits',
      Chip: 'Apple M4 (10-core CPU, 10-core GPU)',
      RAM: '16 GB / 24 GB / 32 GB',
      Storage: '512 GB / 1 TB / 2 TB / 4 TB SSD',
      Battery: '70 Whr, 24-hour',
      OS: 'macOS Sequoia',
      Ports: '3× Thunderbolt 4, HDMI, SD, MagSafe 3',
    },
    colors: ['Space Black', 'Silver'],
    tags: ['M4 Chip', 'Retina XDR', 'Apple Intelligence', 'Pro'],
  },
  {
    id: 9,
    name: 'Apple iPad Pro M4',
    brand: 'Apple',
    category: 'tablets',
    price: 109999,
    originalPrice: 119999,
    image: '/images/tablets/Apple iPad Pro M4.jpeg',
    rating: 4.8,
    reviews: 1760,
    stock: 14,
    isNew: true,
    isFeatured: true,
    description: 'iPad Pro with M4 chip and the first tandem OLED display delivers extraordinary performance in a remarkably thin design. The ultimate tool for creative professionals.',
    specs: {
      Display: '11" / 13" Ultra Retina XDR Tandem OLED, 2388×1668',
      Chip: 'Apple M4 (9-core CPU, 10-core GPU)',
      RAM: '8 GB / 16 GB',
      Storage: '256 GB / 512 GB / 1 TB / 2 TB',
      Camera: '12MP Wide + 10MP Ultra Wide + LiDAR',
      Battery: '10-hour Wi-Fi usage',
      OS: 'iPadOS 17',
      Connectivity: 'Wi-Fi 6E / 5G, USB-C (Thunderbolt 4)',
    },
    colors: ['Space Black', 'Silver'],
    tags: ['M4 Chip', 'OLED', 'Pencil Pro', 'LiDAR'],
  },
  {
    id: 10,
    name: 'Apple iPad Air M4',
    brand: 'Apple',
    category: 'tablets',
    price: 74999,
    originalPrice: 82999,
    image: '/images/tablets/Apple iPad air M4.jpeg',
    rating: 4.7,
    reviews: 1320,
    stock: 20,
    isNew: true,
    isFeatured: false,
    description: 'iPad Air with M4 chip in 11-inch and 13-inch sizes. Light, thin, and incredibly capable. Now with the stunning Liquid Retina display and all-day battery life.',
    specs: {
      Display: '11" / 13" Liquid Retina IPS, 2360×1640',
      Chip: 'Apple M4 (8-core CPU, 9-core GPU)',
      RAM: '8 GB',
      Storage: '128 GB / 256 GB / 512 GB / 1 TB',
      Camera: '12MP Wide + 12MP Ultra Wide (landscape)',
      Battery: '10-hour Wi-Fi usage',
      OS: 'iPadOS 17',
      Connectivity: 'Wi-Fi 6E, USB-C',
    },
    colors: ['Blue', 'Purple', 'Starlight', 'Space Gray'],
    tags: ['M4 Chip', 'Liquid Retina', 'Apple Pencil', 'Air'],
  },
  {
    id: 11,
    name: 'OnePlus Pad 2',
    brand: 'OnePlus',
    category: 'tablets',
    price: 49999,
    originalPrice: 55999,
    image: '/images/tablets/OnePlus Pad2.jpeg',
    rating: 4.5,
    reviews: 860,
    stock: 18,
    isNew: false,
    isFeatured: false,
    description: 'OnePlus Pad 2 features Snapdragon 8 Gen 3, a stunning 12.1" 3K display at 144Hz, and 67W SUPERVOOC charging. A flagship tablet experience at a compelling price.',
    specs: {
      Display: '12.1" LCD, 3000×2120, 144Hz',
      Processor: 'Snapdragon 8 Gen 3 (4nm)',
      RAM: '12 GB',
      Storage: '256 GB',
      Camera: '13MP Rear + 8MP Front',
      Battery: '9510 mAh, 67W SUPERVOOC',
      OS: 'OxygenOS 14 / Android 14',
      Connectivity: 'Wi-Fi 7, Bluetooth 5.4, Stylus support',
    },
    colors: ['Nimbus Gray'],
    tags: ['144Hz', 'Snapdragon 8 Gen 3', '67W Charging', 'Stylus'],
  },
  {
    id: 12,
    name: 'Samsung Galaxy Tab S10 Ultra',
    brand: 'Samsung',
    category: 'tablets',
    price: 119999,
    originalPrice: 129999,
    image: '/images/tablets/Samsung Galaxy Tab S10 Ultra.jpeg',
    rating: 4.8,
    reviews: 980,
    stock: 9,
    isNew: false,
    isFeatured: true,
    description: 'The Galaxy Tab S10 Ultra features a massive 14.6" Dynamic AMOLED 2X display, Snapdragon 8 Gen 3, and Galaxy AI features. Includes the S Pen for a truly premium creative experience.',
    specs: {
      Display: '14.6" Dynamic AMOLED 2X, 2960×1848, 120Hz',
      Processor: 'Snapdragon 8 Gen 3 (4nm)',
      RAM: '12 GB / 16 GB',
      Storage: '256 GB / 512 GB / 1 TB',
      Camera: '13MP + 8MP Rear, 12MP + 12MP UW Front',
      Battery: '11200 mAh, 45W fast charge',
      OS: 'Android 14 / One UI 6.1',
      Connectivity: 'Wi-Fi 7, Bluetooth 5.3, S Pen included',
    },
    colors: ['Graphite'],
    tags: ['14.6" AMOLED', 'S Pen', 'Galaxy AI', 'Snapdragon'],
  },
  {
    id: 13,
    name: 'Samsung Galaxy Tab S10 Ultra (5G)',
    brand: 'Samsung',
    category: 'tablets',
    price: 134999,
    originalPrice: 144999,
    image: '/images/tablets/Samsung Galaxy Tab S10 Ultra2.jpeg',
    rating: 4.8,
    reviews: 560,
    stock: 7,
    isNew: true,
    isFeatured: false,
    description: 'Galaxy Tab S10 Ultra 5G edition. All the power of the Tab S10 Ultra with built-in 5G connectivity for always-on productivity wherever you go.',
    specs: {
      Display: '14.6" Dynamic AMOLED 2X, 2960×1848, 120Hz',
      Processor: 'Snapdragon 8 Gen 3 (4nm)',
      RAM: '16 GB',
      Storage: '512 GB',
      Camera: '13MP + 8MP Rear, 12MP + 12MP UW Front',
      Battery: '11200 mAh, 45W fast charge',
      OS: 'Android 14 / One UI 6.1',
      Connectivity: '5G, Wi-Fi 7, Bluetooth 5.3, S Pen included',
    },
    colors: ['Graphite'],
    tags: ['5G', '14.6" AMOLED', 'S Pen', 'Galaxy AI'],
  },

  // ─── Headphones ────────────────────────────────────────────
  {
    id: 14,
    name: 'Sony WH-1000XM6',
    brand: 'Sony',
    category: 'headphones',
    price: 34999,
    originalPrice: 39999,
    image: '/images/headphones/Sony WH-1000XM6.jpeg',
    rating: 4.9,
    reviews: 3240,
    stock: 30,
    isNew: true,
    isFeatured: true,
    description: 'The Sony WH-1000XM6 takes noise cancellation to an unprecedented level with the new QN3 processor. Auto NC Optimizer, multipoint Bluetooth, and 30-hour battery life redefine premium audio.',
    specs: {
      Type: 'Over-ear, Wireless',
      Driver: '40mm, Liquid Crystal Polymer',
      Frequency: '4 Hz – 40,000 Hz',
      ANC: 'Industry-leading QN3 processor',
      Battery: '30 hrs (ANC on), 3 min = 3 hrs',
      Codec: 'LDAC, AAC, SBC',
      Connectivity: 'Bluetooth 5.3, NFC, 3.5mm',
      Weight: '251 g',
    },
    colors: ['Midnight Black', 'Platinum Silver'],
    tags: ['ANC', 'LDAC', '30hr Battery', 'Best in Class'],
  },
  {
    id: 15,
    name: 'Sony WH-1000XM5',
    brand: 'Sony',
    category: 'headphones',
    price: 29999,
    originalPrice: 34999,
    image: '/images/headphones/Sony WH-1000XM5.jpeg',
    rating: 4.8,
    reviews: 7640,
    stock: 40,
    isNew: false,
    isFeatured: true,
    description: 'Sony WH-1000XM5 with industry-leading noise cancellation, 8 mics, and an all-new lightweight design. Experience music the way it was meant to be heard.',
    specs: {
      Type: 'Over-ear, Wireless',
      Driver: '30mm',
      Frequency: '4 Hz – 40,000 Hz (LDAC)',
      ANC: 'QN1 + QN1e Processors, 8 mics',
      Battery: '30 hrs (ANC on)',
      Codec: 'LDAC, AAC, SBC',
      Connectivity: 'Bluetooth 5.2, NFC, 3.5mm',
      Weight: '250 g',
    },
    colors: ['Midnight Black', 'Platinum Silver'],
    tags: ['ANC', 'LDAC', '30hr Battery', 'Multi-point'],
  },
  {
    id: 16,
    name: 'Bose QuietComfort Ultra Headphones',
    brand: 'Bose',
    category: 'headphones',
    price: 34999,
    originalPrice: 39999,
    image: '/images/headphones/Bose QuietComfort Ultra Headphones.jpeg',
    rating: 4.8,
    reviews: 2890,
    stock: 22,
    isNew: false,
    isFeatured: true,
    description: 'Bose QuietComfort Ultra with Immersive Audio and CustomTune technology. Every mode optimized for your ears, offering an unparalleled listening experience.',
    specs: {
      Type: 'Over-ear, Wireless',
      Driver: 'Proprietary Bose Acoustic',
      Frequency: '20 Hz – 20,000 Hz',
      ANC: 'Bose CustomTune, Immersive Audio',
      Battery: '24 hrs (ANC on), 15 min = 2.5 hrs',
      Codec: 'aptX Adaptive, AAC, SBC',
      Connectivity: 'Bluetooth 5.3, 2.5mm / 3.5mm',
      Weight: '250 g',
    },
    colors: ['Black', 'White Smoke', 'Sandstone'],
    tags: ['Immersive Audio', 'CustomTune', 'ANC', 'Bose'],
  },
  {
    id: 17,
    name: 'OnePlus Buds Pro 3',
    brand: 'OnePlus',
    category: 'headphones',
    price: 11999,
    originalPrice: 14999,
    image: '/images/headphones/OnePlus Buds Pro 3.jpeg',
    rating: 4.4,
    reviews: 1240,
    stock: 35,
    isNew: true,
    isFeatured: false,
    description: 'OnePlus Buds Pro 3 over-ear headphones with 49dB ANC, LHDC 5.0 codec, and 80-hour total playtime. Premium sound meets unbeatable value.',
    specs: {
      Type: 'Over-ear, Wireless',
      Driver: '40mm',
      Frequency: '15 Hz – 40,000 Hz',
      ANC: '49 dB Active Noise Cancellation',
      Battery: '40 hrs (ANC off), 80 hrs (with case)',
      Codec: 'LHDC 5.0, AAC, SBC',
      Connectivity: 'Bluetooth 5.4',
      Weight: '272 g',
    },
    colors: ['Marble White', 'Obsidian Black'],
    tags: ['49dB ANC', 'LHDC 5.0', '80hr Total', 'OnePlus'],
  },

  // ─── Earbuds ───────────────────────────────────────────────
  {
    id: 18,
    name: 'Apple AirPods Pro (2nd Gen)',
    brand: 'Apple',
    category: 'earbuds',
    price: 24999,
    originalPrice: 29999,
    image: '/images/earbuds/Apple AirPods Pro (2nd Generation).jpeg',
    rating: 4.8,
    reviews: 8920,
    stock: 50,
    isNew: false,
    isFeatured: true,
    description: 'AirPods Pro 2 deliver up to 2x more active noise cancellation, Adaptive Transparency, Personalized Spatial Audio with dynamic head tracking, and an MagSafe Charging Case.',
    specs: {
      Type: 'In-ear TWS',
      Driver: 'Custom Apple driver + amp',
      ANC: '2× more ANC, Adaptive Transparency',
      Battery: '6 hrs (ANC on), 30 hrs with case',
      Chip: 'Apple H2',
      Codec: 'AAC, Lossless (Apple devices)',
      Connectivity: 'Bluetooth 5.3',
      'IP Rating': 'IP54',
    },
    colors: ['White'],
    tags: ['H2 Chip', 'ANC', 'Spatial Audio', 'MagSafe'],
  },
  {
    id: 19,
    name: 'Nothing Ear (2024)',
    brand: 'Nothing',
    category: 'earbuds',
    price: 9999,
    originalPrice: 12999,
    image: '/images/earbuds/Nothing Ear (2024).jpeg',
    rating: 4.6,
    reviews: 3450,
    stock: 45,
    isNew: true,
    isFeatured: true,
    description: 'Nothing Ear (2024) with ChatGPT integration, 45dB ANC, and ultra-transparent design. A bold statement in earbuds that sounds as good as it looks.',
    specs: {
      Type: 'In-ear TWS',
      Driver: '11.6mm + 6mm dual driver',
      ANC: '45 dB Active Noise Cancellation',
      Battery: '8.5 hrs, 40.5 hrs with case',
      Chip: 'Nothing X1 + Snapdragon Sound',
      Codec: 'LDAC, AAC, SBC',
      Connectivity: 'Bluetooth 5.3',
      'IP Rating': 'IP54',
    },
    colors: ['White', 'Black'],
    tags: ['45dB ANC', 'LDAC', 'ChatGPT', 'Transparent Design'],
  },
  {
    id: 20,
    name: 'Samsung Galaxy Buds3 Pro',
    brand: 'Samsung',
    category: 'earbuds',
    price: 17999,
    originalPrice: 21999,
    image: '/images/earbuds/Samsung Galaxy Buds3 Pro.jpeg',
    rating: 4.5,
    reviews: 2100,
    stock: 38,
    isNew: true,
    isFeatured: false,
    description: 'Samsung Galaxy Buds3 Pro with blade-inspired design, 24-bit audio, intelligent ANC, and seamless integration with Galaxy AI devices.',
    specs: {
      Type: 'In-ear TWS',
      Driver: '10mm + 5.3mm dual driver',
      ANC: 'Intelligent Noise Cancellation',
      Battery: '6 hrs (ANC on), 26 hrs with case',
      Chip: 'Samsung Custom',
      Codec: 'Samsung Scalable, AAC, SBC',
      Connectivity: 'Bluetooth 5.4',
      'IP Rating': 'IPX7 (buds), IPX4 (case)',
    },
    colors: ['White', 'Silver'],
    tags: ['ANC', '24-bit', 'Blade Design', 'Galaxy AI'],
  },

  // ─── Smartwatches ──────────────────────────────────────────
  {
    id: 21,
    name: 'Apple Watch Series 10',
    brand: 'Apple',
    category: 'smartwatches',
    price: 46999,
    originalPrice: 52999,
    image: '/images/smartwatches/Apple Watch Series 10.jpeg',
    rating: 4.9,
    reviews: 4210,
    stock: 16,
    isNew: true,
    isFeatured: true,
    description: 'Apple Watch Series 10 — the thinnest and lightest Apple Watch ever. With the largest display, faster charging, Sleep Apnea detection, and next-generation health sensors.',
    specs: {
      Display: '46mm / 42mm LTPO OLED, Always-On',
      Chip: 'Apple S10',
      Health: 'ECG, Blood Oxygen, Sleep Apnea, Crash Detection',
      Battery: '18 hrs (standard), 36 hrs (Low Power)',
      OS: 'watchOS 11',
      Connectivity: 'Wi-Fi 6, Bluetooth 5.3, NFC, LTE (optional)',
      'IP Rating': 'Water resistant 50m',
    },
    colors: ['Jet Black', 'Rose Gold', 'Silver', 'Natural Titanium'],
    tags: ['Sleep Apnea', 'ECG', 'Always-On', 'watchOS 11'],
  },
  {
    id: 22,
    name: 'Samsung Galaxy Watch 7',
    brand: 'Samsung',
    category: 'smartwatches',
    price: 29999,
    originalPrice: 34999,
    image: '/images/smartwatches/Samsung Galaxy Watch 7.jpeg',
    rating: 4.6,
    reviews: 2870,
    stock: 24,
    isNew: false,
    isFeatured: false,
    description: 'Galaxy Watch 7 with 3nm chip, Advanced Body Composition analysis, Metabolic Rate measurement, and seamless Galaxy AI health insights.',
    specs: {
      Display: '44mm / 40mm Super AMOLED, Always-On',
      Chip: 'Exynos W1000 (3nm)',
      Health: 'ECG, Blood Oxygen, Advanced Body Composition',
      Battery: '40 hrs (standard), 70 hrs (Power Saving)',
      OS: 'Wear OS 5 / One UI Watch 6',
      Connectivity: 'Wi-Fi 6, Bluetooth 5.3, NFC, LTE (optional)',
      'IP Rating': '5ATM + MIL-SPEC-810H',
    },
    colors:['Green', 'Cream', 'Silver'],
    tags: ['3nm Chip', 'ECG', 'Body Composition', 'Galaxy AI'],
  },
  {
    id: 23,
    name: 'Amazfit Balance',
    brand: 'Amazfit',
    category: 'smartwatches',
    price: 19999,
    originalPrice: 24999,
    image: '/images/smartwatches/Amazfit Balance.jpeg',
    rating: 4.4,
    reviews: 1680,
    stock: 32,
    isNew: false,
    isFeatured: false,
    description: 'Amazfit Balance — a harmony of wellness and style. With AI health management, dual-band GPS, 14-day battery, and premium aluminum body that rivals smartwatches twice its price.',
    specs: {
      Display: '1.5" AMOLED, 480×480, Always-On',
      Chip: 'Zepp OS',
      Health: 'Heart Rate, Blood Oxygen, Stress, Readiness Score',
      Battery: '14 days (standard), 25 hrs GPS',
      GPS: 'Dual-band L1+L5',
      Connectivity: 'Bluetooth 5.0, Wi-Fi',
      'IP Rating': '5 ATM',
    },
    colors: ['Sunset Gold', 'Midnight Black'],
    tags: ['14-Day Battery', 'AI Health', 'Dual GPS', 'AMOLED'],
  },
];

// ─── Helpers ───────────────────────────────────────────────────
export const getProductById = (id) => PRODUCTS.find(p => p.id === Number(id));
export const getProductsByCategory = (cat) =>
  cat === 'all' ? PRODUCTS : PRODUCTS.filter(p => p.category === cat);
export const getFeaturedProducts = () => PRODUCTS.filter(p => p.isFeatured);
export const getNewProducts = () => PRODUCTS.filter(p => p.isNew);

export const SORT_OPTIONS = [
  { value: 'featured',   label: 'Featured' },
  { value: 'price-asc',  label: 'Price: Low to High' },
  { value: 'price-desc', label: 'Price: High to Low' },
  { value: 'rating',     label: 'Top Rated' },
  { value: 'newest',     label: 'Newest First' },
];

export const PRICE_RANGES = [
  { label: 'Under ₹10,000',            min: 0,      max: 10000 },
  { label: '₹10,000 – ₹30,000',        min: 10000,  max: 30000 },
  { label: '₹30,000 – ₹70,000',        min: 30000,  max: 70000 },
  { label: '₹70,000 – ₹1,20,000',      min: 70000,  max: 120000 },
  { label: 'Above ₹1,20,000',          min: 120000, max: Infinity },
];

export const BRANDS = ['Apple', 'Samsung', 'Sony', 'OnePlus', 'Dell', 'Lenovo', 'Bose', 'Nothing', 'Amazfit'];

export const HERO_SLIDES = [
  {
    id: 1,
    title: 'iPhone 16',
    subtitle: 'Hello, Apple Intelligence.',
    desc: 'The most personal iPhone yet. Powered by A18 chip with extraordinary capability.',
    price: '₹89,999',
    image: '/images/mobiles/iphone 16.jpeg',
    color: '#6366f1',
    productId: 1,
  },
  {
    id: 2,
    title: 'Sony WH-1000XM6',
    subtitle: 'Silence the World.',
    desc: 'Industry-leading noise cancellation. 30-hour battery. Pure audio nirvana.',
    price: '₹34,999',
    image: '/images/headphones/Sony WH-1000XM6.jpeg',
    color: '#06b6d4',
    productId: 14,
  },
  {
    id: 3,
    title: 'MacBook Pro M4',
    subtitle: 'Unbelievably powerful.',
    desc: 'M4 chip. Liquid Retina XDR display. Up to 24 hours of battery life.',
    price: '₹1,99,999',
    image: '/images/tablets/Apple MacBook Pro M4.jpeg',
    color: '#8b5cf6',
    productId: 8,
  },
];

export const STATS = [
  { value: '50K+',  label: 'Happy Customers' },
  { value: '23',    label: 'Premium Products' },
  { value: '6',     label: 'Top Brands' },
  { value: '4.8★',  label: 'Average Rating' },
];
